projects:
  hardcover:
    schema:
      - https://api.hardcover.app/v1/graphql:
          headers:
            Authorization: "Bearer ${HARDCOVER_BEARER_TOKEN}"
    documents: "src/queries/hardcover.graphql"
  github:
    schema:
      - https://api.github.com/graphql:
          headers:
            Authorization: "Bearer ${GITHUB_ACCESS_TOKEN}"
    documents: "src/queries/github.graphql"