query Me {
    me {
        id
        want_to_read: user_books(where: { status_id: { _eq: 1 } }) {
            id
            rating
            book {
                id
                title
                pages
                slug
                image {
                    url
                }
                contributions {
                    author {
                        name
                    }
                }
            }
        }
        currently_reading: user_books(where: { status_id: { _eq: 2 } }) {
            id
            rating
            book {
                id
                title
                pages
                slug
                image {
                    url
                }
                contributions {
                    author {
                        name
                    }
                }
            }
        }
        read: user_books(where: { status_id: { _eq: 3 } }) {
            id
            rating
            book {
                id
                title
                pages
                slug
                image {
                    url
                }
                contributions {
                    author {
                        name
                    }
                }
            }
        }
    }
}